version: '3'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  service:
    image: service:latest
    container_name: service
    ports:
      - "8000:8000"
    environment:
      - SERVICE_DB_NAME=postgres
      - SERVICE_DB_USER=postgres
      - SERVICE_DB_PASS=postgres
      - SERVICE_DB_HOST=db
      - SERVICE_DB_PORT=5432
      # - SERVICE_EXCLUDE_EMPLOYEE_FIELDS=email,phone_number
